# -*- coding: utf-8 -*-
"""
@Date : 2026-03-04
@Author : xiezizhe
"""

import json
import logging
import os
from typing import Dict, List

from csc_ai_deep_mining.schema.document import Document, DialogueLog
from csc_ai_deep_mining.schema.research_question import ResearchQuestion
from csc_ai_deep_mining.schema.evidence import Evidence, ResearchResult
from csc_ai_deep_mining.config import config

from .graph import researcher_graph
from .nodes import parse_json_from_llm

logger = logging.getLogger(__name__)

class ResearcherAgent:
    """
     Phase II Agent of DeepMining.
     Responsible for taking Research Questions generated by the Planner
     and seeking answers from the Document corpus using a LangGraph workflow.
    """
    
    def __init__(self, prompt_path: str = None):
        if prompt_path is None:
            language = config.language
            suffix = "_zh_CN" if language == "zh_CN" else ""
            self.prompt_template_path = os.path.join(
                os.path.dirname(__file__), 
                f"../../prompts/researcher_agent{suffix}.md"
            )
        else:
            self.prompt_template_path = prompt_path
            
        with open(self.prompt_template_path, 'r', encoding='utf-8') as f:
            self.system_prompt_template = f.read()
            
        import threading
        self._setup_lock = threading.Lock()

    def _render_prompt(self, rq: ResearchQuestion) -> str:
        """
        Renders the system prompt template with specific Research Question details.

        Args:
            rq (ResearchQuestion): The specific question and constraints to inject.

        Returns:
            str: The fully instantiated system prompt ready for the LLM.
        """
        prompt = self.system_prompt_template
        prompt = prompt.replace("{{ user_intent }}", rq.user_intent)
        prompt = prompt.replace("{{ constraints }}", "\n".join(rq.constraints) if rq.constraints else "None")
        prompt = prompt.replace("{{ question_text }}", rq.question_text)
        return prompt

    def investigate(self, rq: ResearchQuestion, documents: List[Document], dialogue_logs: List[DialogueLog] = None) -> ResearchResult:
        """
        Executes the researcher workflow for a specific Research Question.

        Initializes the LangGraph state and runs the `think` -> `tool` cycle
        until the AI agent concludes the investigation or reaches a recursion limit.
        Extracts final evidence and conclusions into a structured result.

        Args:
            rq (ResearchQuestion): The defined objective for the researcher.
            documents (List[Document]): The local corpus of documents to search against.
            dialogue_logs (List[DialogueLog]): Optional list of historical support dialogues.

        Returns:
            ResearchResult: A packaged result containing the gathered evidence
                and a synthesized conclusion answering the original query.
        """
        logger.info(f"Starting investigation for RQ: {rq.question_text}")
        
        system_content = self._render_prompt(rq)
        
        # Build tools if not already built (lazy evaluation cache for thread safety)
        if hasattr(self, '_setup_lock'):
            with self._setup_lock:
                if not hasattr(self, "search_tool"):
                    from .tools import create_search_documents_tool, create_search_dialogue_log_by_pageindex_tool
                    logger.info("Building global PageIndex tools for ResearcherAgent...")
                    self.search_tool = create_search_documents_tool(documents)
                    self.dialogue_tool = create_search_dialogue_log_by_pageindex_tool(dialogue_logs) if dialogue_logs else None
        else:
            # Fallback if unthreaded
            if not hasattr(self, "search_tool"):
                from .tools import create_search_documents_tool, create_search_dialogue_log_by_pageindex_tool
                logger.info("Building global PageIndex tools for ResearcherAgent...")
                self.search_tool = create_search_documents_tool(documents)
                self.dialogue_tool = create_search_dialogue_log_by_pageindex_tool(dialogue_logs) if dialogue_logs else None
                
        # Initialize internal state for the graph
        initial_state = {
            "messages": [HumanMessage(content=system_content, name="system_init")],
            "research_question": rq,
            "documents": documents,
            "dialogue_logs": dialogue_logs or [],
            "search_tool": self.search_tool,
            "dialogue_tool": self.dialogue_tool,
            "search_queries": [],
            "evidence_list": [],
            "conclusion": "",
            "is_fully_answered": False
        }
        
        # Execute the LangGraph
        config = {"recursion_limit": 15}  # Prevent infinite loops
        try:
            final_state = researcher_graph.invoke(initial_state, config=config)
        except Exception as e:
            logger.error(f"LangGraph execution failed: {e}")
            return ResearchResult(
                research_question=rq,
                evidence_list=[],
                conclusion=f"Investigation failed due to internal error: {e}",
                is_fully_answered=False
            )
            
        # Parse output from the last message in the state
        last_message = final_state.get("messages", [])[-1]
        
        # Extract the JSON block
        if isinstance(last_message, AIMessage):
            parsed = parse_json_from_llm(last_message.content)
        else:
            parsed = parse_json_from_llm(getattr(last_message, "content", "{}"))
            
        is_fully_answered = parsed.get("is_fully_answered", False)
        conclusion = parsed.get("conclusion", "No conclusion provided.")
        sop_baseline = parsed.get("sop_baseline", "")
        observed_patterns = parsed.get("observed_patterns", "")
        identified_anomalies = parsed.get("identified_anomalies", "")
        raw_evidence = parsed.get("evidence_list", [])
        raw_tool_usages = parsed.get("tool_usages", [])
        
        evidence_objects = []
        for e in raw_evidence:
            try:
                evidence_objects.append(Evidence(
                    id=e.get("id", "unk_id"),
                    source_doc_id=e.get("source_doc_id", "unk"),
                    content=e.get("content", ""),
                    relevance_score=float(e.get("relevance_score", 1.0))
                ))
            except Exception as e_err:
                logger.warning(f"Failed to parse evidence object: {e_err}")
                
        # Import ToolUsage specifically for this parsing
        from csc_ai_deep_mining.schema.evidence import ToolUsage
        
        tool_usage_objects = []
        for t in raw_tool_usages:
            try:
                tool_usage_objects.append(ToolUsage(
                    tool_name=t.get("tool_name", "unknown_tool"),
                    input_args=t.get("input_args", {}),
                    output_result=t.get("output_result", "")
                ))
            except Exception as t_err:
                logger.warning(f"Failed to parse tool usage object: {t_err}")
                
        return ResearchResult(
            research_question=rq,
            evidence_list=evidence_objects,
            tool_usages=tool_usage_objects,
            conclusion=conclusion,
            sop_baseline=sop_baseline,
            observed_patterns=observed_patterns,
            identified_anomalies=identified_anomalies,
            is_fully_answered=is_fully_answered
        )
