# -*- coding: utf-8 -*-
"""
@Date : 2026-03-05
@Author : xiezizhe
"""

from typing import List, Optional
from pydantic import BaseModel, Field

class SOPNode(BaseModel):
    """
    Represents a discrete step or state within the generated Customer Service SOP Graph.
    """
    id: str = Field(..., description="Unique alphanumeric identifier for the node (e.g., 'A', 'B1')")
    label: str = Field(..., description="The human-readable description of the step/action")
    node_type: str = Field(default="action", description="The type of the node: 'action', 'dialogue', 'decision'")
    attached_skills: List[str] = Field(default_factory=list, description="List of AtomicSkill names associated with executing this node")
    
class SOPEdge(BaseModel):
    """
    Represents a transition or conditional path between two SOPNodes.
    """
    source_id: str = Field(..., description="The ID of the originating node")
    target_id: str = Field(..., description="The ID of the destination node")
    condition: str = Field(default="", description="The specific condition required to traverse this edge (e.g., 'Yes', 'User Angry')")

class SOPGraph(BaseModel):
    """
    Represents the full structural roadmap of standard operating procedures generated by the Analyst.
    """
    scenario_name: str = Field(..., description="The name of the overall scenario this graph represents")
    nodes: List[SOPNode] = Field(default_factory=list, description="All individual steps within the SOP")
    edges: List[SOPEdge] = Field(default_factory=list, description="All transitions connecting the steps")
    
    def to_mermaid(self) -> str:
        """
        Builds a Mermaid 'graph TD' formatted string representing the SOP.
        Adheres to specific stylistic choices for different node types.
        """
        lines = ["graph TD"]
        lines.append(f'    subgraph "{self.scenario_name}"')
        
        # Add Nodes with shapes based on type
        for node in self.nodes:
            clean_label = node.label.replace('"', "'")
            # For decisions use diamond brackets {}
            if node.node_type == "decision":
                lines.append(f'        {node.id}{{"{clean_label}"}}')
            # For internal states use rounded ()
            elif node.node_type == "state":
                lines.append(f'        {node.id}("{clean_label}")')
            # For standard dialogue or system actions use standard brackets []
            else:
                lines.append(f'        {node.id}["{clean_label}"]')
                
        lines.append("") # Blank space
        
        # Add Edges
        for edge in self.edges:
            if edge.condition:
                clean_cond = edge.condition.replace('"', "'")
                # Ensure the condition string behaves gracefully if long
                lines.append(f'        {edge.source_id} -- "{clean_cond}" --> {edge.target_id}')
            else:
                lines.append(f'        {edge.source_id} --> {edge.target_id}')
                
        lines.append("    end")
        return "\n".join(lines)
